### ISSUE TITLE
ADD VMWare's Docker Registry

### ISSUE THREAD

**Issue by endersonmaia** [veggiemonk/awesome-docker#219]
An enterprise-class container registry server based on Docker Distribution http://vmware.github.io/harbor/

**Comment by endersonmaia** [comment]
I didn't know which section, so I created an issue instead of a PR.

**Comment by vegasbrianc** [comment]
Hi @endersonmaia Thanks for opening the issue. You are correct as the section was not really clear. I've since updated the section name to Storing Images and Registries to make it a little clearer. I've added your suggestion and the commit is here - https://github.com/veggiemonk/awesome-docker/commit/91491e85c5c09cba2bec541aa4959456b2175ea7
