### ISSUE TITLE
Update http://veggiemonk.github.io/awesome-docker/

### ISSUE THREAD

**Issue by JensPiegsa** [veggiemonk/awesome-docker#254]
Hi folks,

the current [github.io](http://veggiemonk.github.io/awesome-docker/) page doesn't reflect the latest changes on this list.
I wonder whether the static site generator is triggered once in a while.

Cheers
Jens

**Comment by veggiemonk** [comment]
Hi @JensPiegsa 
Yes the site generator is triggered regularly but not automatically yet (unfortunately)
Especially since Github changed the theming to Jekyll, I had to make sure of a few things before switching to new format.

I haven't research the topic further because all automatic solution relies on build passing tests.
It's fine for software but for this kind of repo, a "generate on merge" would be preferable.
If you know any way to automatically do this, I'll be thankful. I can give you access to the repo if you know how to set this up!

Thanks for opening an issue, it really give the incentive to fix this once and for all because it has been bothering me for a while. 

Cheers,

Julien

**Comment by gesellix** [comment]
Not sure if that's an option for you @veggiemonk , but I use [Netlify](https://www.netlify.com/) for my generated static content.

**Comment by veggiemonk** [comment]
@gesellix Thanks a lot, it looks super interesting for front-end projects...

I will have to research this a little bit further, I don't know how the other awesome projects keep the github pages in sync after a merge!
The other solution would be a weekend hack with a backend on heroku or something! 
it has been added to my to do list, if anyone is interested in tackling the problem, I can offer access to the repo.

**Comment by veggiemonk** [comment]
@JensPiegsa @gesellix @vegasbrianc 

Hi follows,

Just FYI, now the website is automatically and **instantly** updated. 

It was really simple actually. Don't know why didn't think of it before.

Here is the solution for those interested. Just convert markdown to html (showdown.js works great!) on the fly and the CSS will do the rest. 

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.1/fetch.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.5.4/showdown.min.js"></script>
    <script>
      const converter = new showdown.Converter();
      const text      = fetch('https://raw.githubusercontent.com/veggiemonk/awesome-docker/master/README.md')
                        .then(res => res.text())
                        .catch(err => console.error(err))
                        .then( text => {
                          document.getElementById('md').innerHTML = converter.makeHtml(text);
                        });
    </script>
```

If you have any suggestion, open an issue. 

Thank to you all for your contribution 😄  It is really appreciated.

Julien
