### ISSUE TITLE
Docker for Offline Deployments (video)

### ISSUE THREAD

**Issue by mjhea0** [veggiemonk/awesome-docker#524]
Hi,

I would like to add a link. It's for a video.

**TITLE**: Simplifying Offline Python Deployments With Docker

**URL**: https://youtu.be/d-buWgENj3Y

**Comment by veggiemonk** [comment]
Hi @mjhea0,

Thank you for sharing the link. That video in the link is quite specific to deploying Python app and not really about Docker. I don't think that this video is relevant for this list otherwise we would need a video like that for most common programming languages and that can get quite tedious to maintain. Maybe try some other awesome list: https://github.com/vinta/awesome-python

Thank you for contributing and don't hesitate to let us know if you need us to review a project.

The awesome docker team
